from dotenv import load_dotenv
import os
from openai import OpenAI

data = """# GHSL-2024-255: Possible secret exfiltration and repository manipulation via environment variable injection in docker-mailserver

docker-mailserver docs-preview-deploy.yml workflow is vulnerable to Environment Variable injection which may lead to secret exfiltration and repository manipulation.

docker-mailserver

Latest commit at the time of reporting.

The docs-preview-deploy.yml workflow gets triggered when the Documentation (PR) workflow completes:

Later, it downloads and extracts an artifact generated by the triggering workflow:

And reads pr.env into the runner’s Environment Variables:

The $GITHUB_ENV pointed file is just a regular file where every KEY=VALUE will be used to define a new Environment Variable after the step completes. Since the contents of the pr.env may be controlled by an attacker, they will be able to inject any new Environment Variables in the runner.

An attacker can send a malicious inject.so and pr.env file with the following content as part of a pull request:

Which will result in a new Environment Variables being defined:

In this example we are manipulating the LD_PRELOAD environment variable to force the system to load a malicious shared library called inject.so. As a result, all subsequent processes launched will automatically incorporate this compromised library into their execution environment.

The following steps will run the node command and, therefore, the LD_PRELOAD will execute arbitrary code when node gets executed:

This issue will grant a malicious actor full write permissions:

In addition, the following secrets will get exposed to the attacker: secrets.NETLIFY_AUTH_TOKEN and secrets.NETLIFY_SITE_ID

This issue was discovered and reported by GHSL team member @pwntester (Alvaro Muñoz).

You can contact the GHSL team at securitylab@github.com, please include a reference to GHSL-2024-255 in any communication regarding this issue.
"""
load_dotenv()

def save_to_file(content, folder_name):
    """保存内容到指定文件夹下的文件中"""
    filename = generate_filename(content)
    file_path = os.path.join(folder_name, filename)
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(content)
    print(f"内容已保存至 {file_path}")
    return file_path

def remove_markdown_tags(content):
    lines = content.splitlines()
    # 过滤掉第一个 ```markdown 和最后一个 ```
    if lines[0].startswith("```markdown"):
        lines = lines[1:]
    if lines[-1] == "```":
        lines = lines[:-1]
    return "\n".join(lines)

def convert_with_openai(data):
    client = OpenAI()
    question = f"""使用最简单的表达方式，重新描述下面内容，使得人们更易于看明白。重点在于介绍清楚技术基础知识点，以markdown格式输出。
-----------
{data}
"""
    completion = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": question}
        ]
    )

    content = completion.choices[0].message.content
    content = remove_markdown_tags(content)
    print(content)
    return(content)

def main():
    convert_with_openai(data)

if __name__ == "__main__":
    main()
